# Generated by Django 3.0.6 on 2020-07-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='style',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='unit',
            name='mesaure',
            field=models.CharField(choices=[('VOLUME', 'Volume'), ('MASS', 'Mass')], default='VOLUME', max_length=20),
        ),
    ]
