# Generated by Django 3.0.6 on 2020-07-13 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_store', '0002_auto_20200713_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='mesaure',
            new_name='measure',
        ),
    ]
