# Generated by Django 3.0.6 on 2020-07-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_store', '0003_auto_20200713_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='abbreviation',
            field=models.CharField(default='TBD', max_length=5),
        ),
    ]
