# Generated by Django 3.0.6 on 2020-07-13 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_store', '0005_auto_20200713_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='measure',
        ),
    ]
